menu:
  #关于: /about
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  #链接: /links

excerpt_link: 阅读全文
post_at: 发表于

#google_analytics: UA-32857089-1

#rss: http://feeds.feedburner.com/willerce

#comment_provider: duoshuo
#Duoshuo comment
#duoshuo:
  #short_name: willerce
